[package]
name = "rte-sys"
version = "0.1.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "FFI bindings to DPDK"
links = "dpdk"
build = "build.rs"

[dependencies]
log = "0.3"
libc = "0.2"

[dev-dependencies]


[build-dependencies]
log = "0.3"
env_logger = "0.3"
gcc = "0.3"
regex = "0.1"
