[package]
name = "rte-build"
version = "20.11.0"
authors = ["Flier Lu <flier.lu@gmail.com>"]
description = "FFI bindings to DPDK 19.11"

[dependencies]
log = "0.4"
lazy_static = "1.4"
raw-cpuid = "8.1"
itertools = "0.9"
num_cpus = "1.13"
cc = "1.0"
pkg-config = "0.3"
